--- 
AWSTemplateFormatVersion: "2010-09-09"
Description: "Create splaysh web CFN assets"
Parameters:
  EnvironmentTag:
    Type: String
    Description: Environment of the Stack
    Default: "dev"
  ReadCapacityUnits:
      Type: Number
      Description: default DynamoDB provisioned Read capacity
      Default: "1"
  WriteCapacityUnits:
      Type: Number
      Description: default DynamoDB provisioned Write capacity
      Default: "1"
Resources:
  itemstable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Join [ ".", [ "splayshdb", Ref: EnvironmentTag, items ] ]
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
        -
          AttributeName: "nut_type"
          AttributeType: "S"
        -
          AttributeName: "create_date"
          AttributeType: "S"
        -
          AttributeName: "is_public"
          AttributeType: "N"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
          ReadCapacityUnits:
            Ref: ReadCapacityUnits
          WriteCapacityUnits:
            Ref: WriteCapacityUnits
      GlobalSecondaryIndexes:
        -
          IndexName: "item-nut-createdate"
          KeySchema:
            -
              AttributeName: "nut_type"
              KeyType: "HASH"
            -
              AttributeName: "create_date"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits:
              Ref: ReadCapacityUnits
            WriteCapacityUnits:
              Ref: WriteCapacityUnits
        -
          IndexName: "item-ispublic-createdate"
          KeySchema:
            -
              AttributeName: "is_public"
              KeyType: "HASH"
            -
              AttributeName: "create_date"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits:
              Ref: ReadCapacityUnits
            WriteCapacityUnits:
              Ref: WriteCapacityUnits